### ISSUE TITLE
Fiori Segmented Button has no method to get Selected Key value

### ISSUE THREAD

**Issue by guymonlh** [org-scn-design-studio-community/sdkpackage#104]
Added the Fiori Segmented Button to my UI and love it.   I do not see a method on this component to get the Selected Key value so I can do something based on the button selection in the On Select event. Perhaps I missed it????

**Comment by MartinPankraz** [comment]
Hi guynonlh,

You are absoultely right. That was missing. I added it just now. With the next build of the repository it will be populated.

Kind regards
Martin
