### ISSUE TITLE
Gauge 3.0 issues

### ISSUE THREAD

**Issue by shlomiweiss** [org-scn-design-studio-community/sdkpackage#105]
Hi,
 
There is something with the start and end values
when I set the start value to 40 for example and the indicator value is 25, the needle will stand on 40 and that't OK.
On the end side, if the end is set to 80 for example and the indicator value is 100, the needle will go beyond 80 and even back over the start value.
I believe that it should work the same way on both sides

One more thing that I've noticed
the start and end values work fine (besides what I've described earlier)
but the Second and Third color does not work right
 
Please see an example
Start value 40
end value 60
Start of second color 45
Start of third color 55
 
It seems that the work against a 0 basis and not against the modified start and end
values

Please find attached a screenshot + application sample file
[DS_Support.zip](https://github.com/org-scn-design-studio-community/sdkpackage/files/225462/DS_Support.zip)

![capture19042016](https://cloud.githubusercontent.com/assets/10007514/14631916/7606a9d2-061e-11e6-82a2-d0b9d65f45e7.PNG)

Thanks

Shlomi

**Comment by jbakke16** [comment]
I'm running into the same issue into situations where the start value will range from 90-95 and the end value will range from 100-110. It is a small range but I can't seem to get it to work either. Thanks,
Jake
