### ISSUE TITLE
Document for methods and attributes of class "sap.designstudio.sdk.DataBuffer"

### ISSUE THREAD

**Issue by ngoclong19** [org-scn-design-studio-community/sdkpackage#109]
(Original posted on http://scn.sap.com/community/businessobjects-design-studio, but was rejected by an SCN moderator, http://scn.sap.com/thread/3894053, and he directed me here.)

From the example _com.sap.sample.scalingdatasource_, we can see class _ScalingDataSource_ inherited method _addResult_ and attribute _buffer_ from its parent class _DataBuffer_.

Is there any document about these methods and attributes available? As I can't find them in the Developer Guide.

Thank you!

**Comment by KarolKalisz** [comment]
hmm, this is more a question to SDK API, not to the community components. Lets see if Mike will be able to answer. I can try to check if someone from development can pick this (and perhaps also update the documentation of data buffer)

**Comment by KarolKalisz** [comment]
Hi,

have you actually checked the SDK documentation?
In general, the DataBuffer is documented in SDK guide.
http://help.sap.com/businessobject/product_guides/AAD16/en/ds_16SP01_dev_guide_en.pdf 
7.4 Option 2: Extending the DataBuffer JavaScript Class

as far I can see, this method is missing there, I have asked my colleagues to check 8and update as soon it is possible) the documentation.

Karol

**Comment by KarolKalisz** [comment]
Closing as no more response since many months.
