### ISSUE TITLE
that.props and Changed attribute

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#112]
Hi,

I kinda managed to get my new extension working, but for now my issue is: I don't want to redraw my div content each time afterUpdate is called.
For that, I was thinking about checking which attribute has been updated, and decide if it requires to rebuild the dom content.

I saw an attribute "changed" for all Spec attribute declared, and this value can either contains true or false. But, as far as I checked, it's always true.

How do you handle this scenario ?

Thanks.

**Comment by franckblais** [comment]
Another question: how to sort APS controls in a tab ?

I'm looking at what has been developed and the code as well, but no luck for now.

**Comment by franckblais** [comment]
![image](https://cloud.githubusercontent.com/assets/10117707/14825851/870f66f2-0ba9-11e6-9fe8-23b0f57db6d2.png)
Managed to understand, but I am using Description to do that ... not exactly what I hoped :)

**Comment by franckblais** [comment]
For changing attribute and avoiding recreating the DOM, I managed with the beforeUpdate and comparing values.
The only thing left is about the data ... I didn't see how I can know when it has been changed. I only think of using a custom ZTL function to update a flag instead of the APS 3.0 generated ones.

Any advice ?

**Comment by entmike** [comment]
I think I had an "order" parameter in the APS config to control order.
Basically, after it figures out its category, i think next it sorts by
alphanumeric, and then optionally, order.  I think Karol at one point may
have changes checkboxes to always be at top but I may have overridden
this.  I know I have a forked version of this APS that has complete order
control, if you are having problems, i can incorporate into the SCN one.

On Tue, Apr 26, 2016 at 11:23 AM, franckblais <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/10117707/14825851/870f66f2-0ba9-11e6-9fe8-23b0f57db6d2.png>
> Managed to understand, but I am using Description to do that ... not
> exactly what I hoped :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/112#issuecomment-214800720>
>



-- 
Mike Howles

**Comment by franckblais** [comment]
I mean it works with the description, but it's not optimal, that's all.
If you think it's worth it, yeah, including the order would be great.

For data, I think I'll give a try by, at runtime:

- rename the generated set/get data function
- create a specific function and calling the previously copied ones
- add a control flag to update the component.

**Comment by franckblais** [comment]
Hi !

Just to let you know I've implemented order support in APS. in "opts", just add "order": with the priority (numeric).
I'll push the code today.

**Comment by entmike** [comment]
Awesome, great job braving the APS code ;)

**Comment by franckblais** [comment]
Actually it was really simple ^^but thanks ;)

On Mon, Jun 6, 2016 at 9:31 AM, Mike Howles <notifications@github.com>
wrote:

> Awesome, great job braving the APS code ;)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/112#issuecomment-223959378>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJpiSylsdiXYGDEDsVJm_zFU7LPeFo3oks5qJCFPgaJpZM4IO8hs>
> .
>



-- 
Franck BLAIS
