### ISSUE TITLE
Embedded frame 2.0 issue 

### ISSUE THREAD

**Issue by JosephineLandgraf** [org-scn-design-studio-community/sdkpackage#113]
Dear all,
I am facing the following issue with the Embedded frame 2.0 component in my Design Studio application (I am using Design Studio 1.6):
I have several Design studio applications that I try to display in frames in one big container application.
Every Embedded frame is lying on a separate page on a separate panel:
![2016-04-26_10-13-11](https://cloud.githubusercontent.com/assets/18678819/14816389/ea0b3bd0-0bb0-11e6-85b9-370eae1a39fa.jpg)

The Embedded frame lying on the HOME_PANEL that is visible upon start-up is loading and showing the correct application without any issue.

If I now try to switch to a different page with the setPagebyName command, setting the correct URL for the Embedded frame lying on the corresponding panel of the page, the next page is not loading and set visible and the Embedded application is not showing. The page will just keep on loading, but no changes are going to show.
Any ideas how I could work around this?

Thanks a lot.
Best regards,

Josephine

**Comment by franckblais** [comment]
Hi,

On a general note, I noticed a tabstrip is destroying the content of the non active tabs. You may have to check if the same behavior applies for the pagebook ... Just a thought.
If so, maybe the caching of other pages could help.

**Comment by MartinPankraz** [comment]
Hi Josephine,

I just checked what you describe with two embeddedFrame components and two different web sites I commonly use. That works like a charm. Why would you be setting the url during runtime anyway? Is that somehow dynamic except for the navigation on the pagebook? If not the url can be assigned during designtime already.

It is very likely that your target website has problems running in an IFrame. You should check that first. The components are fine.

Let us know how that goes.

Regards
Martin

**Comment by KarolKalisz** [comment]
I would suggest to not use pagebook. What about following solution?

* make some panels with the frames
* build your "own pagebook" which would move the panels from non-visible areas to visible area
setLeftMargin(-2000)
and
setLeftMargin(0)

by this, all frames will load when visible (visible means also in HTML but in non-visible area) and when changing the panel/frames you would get always the same content which you left.

Karol

**Comment by sreenichinta** [comment]
Martin & Karol,
it seems none of suggestions are working in my case in DS 1.6

![capture](https://cloud.githubusercontent.com/assets/20972340/17592189/db05d08a-5ffe-11e6-82d7-8e3b6354b15b.PNG)

two buttons are just sample buttons & it has empty code in OnClick event.
By default Both Embedded frames are loading side by side, if i click on any button it keep on loading....

Please give us some solution..

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

Could you please post the ouput of the devloper console of your browser? Hit F12 and find the console after the error appeared. There should be an error regarding your problem. We might be able to pin point it from there. I suspect domain security problems.

Please also let us know if you are running locally or on BIP.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Thank you very much Martin,
I am getting access denied error..
If i am running locally there is no issue, issue in BIP.

![capture2](https://cloud.githubusercontent.com/assets/20972340/17612996/e1cc9bac-6075-11e6-91ab-dc1ff51bca82.PNG)

**Comment by MartinPankraz** [comment]
Hi Sreeni,

In that case you can try to run directly through the OpenDocument service. To do so go into the BI launchpad and locate your dashboard (under Documents or our favorites), right click it and choose Document Link. On the next screen you will find your dashboards open document link. Add the following to its URL "&noDetailsPanel=true". Use that modified link to test again. Be aware that the BO server rewrites it once executed. You will have to remember the initial link to execute again. Refreshing the page stops working once the timeout hits you.

Let us know.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Thank you very much Martin,
I am not able to change or add "&noDetailsPanel=true" to document link.
Let me explain you my requirement, We have home page which has 10 Tabstrips each Tab has couple of buttons & each button will have separate report which will embedded in to Home Page.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

Maybe we misunderstand each other. In order to call your Design Studio dashboard you have to use a link for sure. This link can be an OpenDocument link. Thus you can manipulate it for sure.

Even if you are looking to integrate other dashboards using the embedded frame you have to define a source url. There you can add as well.

It does not matter what other components you use on your dashboard. Your problem originates from browser security, prohibiting calls to sources outside of your server domain. My first suggestion to workaround that was to avoid one layer of nesting on the BO side by skipping the BI launchpad and using the OpenDocument link only. I gave you directions to that.

If all of this doesn't help, you will need to start thinking of setting up a reverse proxy which masks the call to that outside domain and satisfies the browser security policy.

Kind regards
Martin

**Comment by MartinPankraz** [comment]
Hi Sreeni, hi Josephine

I just added a new option to the embedded frame that allows to avoid setting the iframes location property explicitly. That helped me in a nested IFrame scenario.

The next repository build will contain the new option. @KarolKalisz: Can you trigger a rebuild? 

Let me know if that solves your problem.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
Thanks for your work around solution & it works :+1: 
but identified one more issue if my browser ideal for couple of minutes & try to access my TABS in TABSTRIP it reloading page with out work around solution ("&noDetailsPanel=true"). do you have any comments. if this the case then getting old issue.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

The timeout you experience is actually an OpenDocument service bug. You can check sap note 2268092 on how to fix the bug. But be aware that this will cause my workaround to no longer work.

Actually with my last post I wanted you to check the new Design Studio option on the Embedded Frame called "Explicitly set document domain" -> false. To see if that already fixes your problem without the noDetailsPanel option. The new repository build is not yet done though.

@entmike Can you lend me a hand here?

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,

Please let me know if new repository build is ready, we will test.

@entmike Please make it ASAP.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

I uploaded an offline Version of the repository so you don't have to wait for the public rebuild. Contact me on SCN and I will Forward you the offline donwload link.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
Permanent fix did not work.
Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

This was just an additional option for domain settings. If your domains differ this would never have helped. You need to look into your IT infrastructure to solve this.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
I am really sorry i forgot to implement this "Explicitly set document domain" -> false

And really thankful to your fix, it works :+1:  :+1: 

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

Thanks for the heads up.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
It open new issue..

We have home page which has 10 Tabstrips each Tab has couple of buttons & each button will have separate report which will embedded in to Home Page.
But now it overwrite home page with other new report when i select any of my button.
it should embedded in to home page.

Thanks,
Sreeni.

**Comment by sreenichinta** [comment]
Martin,

Please don't close this issue, it triggers new issue.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

New issue means new ticket. Please open a new one outlining your problem with some details.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,

it arises with our changes because of changes.

Thanks,
Sreeni.
