### ISSUE TITLE
Activity viewer - support of time when defining task start/end

### ISSUE THREAD

**Issue by hlebc** [org-scn-design-studio-community/sdkpackage#115]
Activity viewer supports only date when defining tasks (activitys) start and end (YYYYMMDD). It would be great for use cases with shorter activities to support also time (YYYYMMDDHHMMSS).

Thanks and keep up great work :)

**Comment by KarolKalisz** [comment]
try it now, it should work with the new version of today.

**Comment by hlebc** [comment]
Works like a charm - thanks!
