### ISSUE TITLE
Activity Viewer - Activity Description position on chart

### ISSUE THREAD

**Issue by emirado** [org-scn-design-studio-community/sdkpackage#116]
Activity descriptions I need to present on the chart have quite long titles and I'd like to see those horizontally and centered vertically, best with the option to wrap the text. CSS in DS allows me to modify .text class, but as I checked the position is set by transform: translate(x,y) function, which cannot be accessed from DS. x and y parameters are must be set dynamically using javascript I guess.
Any advice and suggestions will be greatly appreciated. Thank you.

**Comment by KarolKalisz** [comment]
please check the settings in Display area, there are 2 settings for change in positions of the text - you can move them (x + Y) and there is one for the angel.
