### ISSUE TITLE
Design Studio 1.6 SP01 - But need RealDate 

### ISSUE THREAD

**Issue by HenryTaylor** [org-scn-design-studio-community/sdkpackage#117]
I have the 1.6 SDK 3.0 installed.  But I need the RealDate component.  Is there a way to have both the 2.0 and the 3.0 SDK versions installed at the same time?  I tried just installing it, but it errors with "Conflicting Dependency" errors.

**Comment by entmike** [comment]
RealDate component in 3.0 is available by right-clicking Technical Components.  No need to install 2.0 for this.

**Comment by HenryTaylor** [comment]
I did not realize that.  Thank you.
