### ISSUE TITLE
Embedded Frame, Opernurlinplace

### ISSUE THREAD

**Issue by karthikBIBO** [org-scn-design-studio-community/sdkpackage#122]
Hello Gurus -
 
I am using the above mentioned SDK components developed by SCN community in our dashboards. I want to install those on the BIP platform now. I am planning to install only those i use. Can someone please advise on how can i extract the only selected  components from the SCN list

I want to extract Emebedded frame 2.0 and openurlinplace components and install only those. 

Thanks in advance  
 
Thanks
Karthik

**Comment by MartinPankraz** [comment]
Hi Karthik,

If you are using our repository installation it is not possible to select only parts of the package.

You would need to clone the code and throw away the unwanted components and re-bundle the repository to achieve what you want. That task is not explained easily in a few words. Ask yourself if it is worth the effort to skip some components when deploying on the server..

Kind regards
Martin
