### ISSUE TITLE
Blank Screen After Upgrade to DS 1.6 SP2

### ISSUE THREAD

**Issue by EviWi** [org-scn-design-studio-community/sdkpackage#127]
After Upgrade to SP2 our DS.Applikation does not render anymore. Blank screen is shown. Firebug reports error in microchart library. We use MicroBulletChart and JSON object in our dashboard.
![image](https://cloud.githubusercontent.com/assets/15331182/16128900/cfadc508-3402-11e6-8416-bb2823a3f6af.jpeg)

**Comment by EviWi** [comment]
You can reproduce the issue: Just add component BULLETMICROCHART to a new dashboard using DS 1.6 SP2. Attached the browser log from preview.
[SP2_microchart.txt](https://github.com/org-scn-design-studio-community/sdkpackage/files/319911/SP2_microchart.txt)

**Comment by EviWi** [comment]
We have reported the issue to SAP support and got this answer today:
"Dear customer,

the issue is fixed. It will be part of Design Studio 1.6 SP 3.
So far there is an easy workaround, stay on Design Studio 1.6 SP 1 until SP 3 is out.
I expect that you found this regression in your test system and thus this should not be a problem to stay on the older release until the issue is relesed.

One background information: the UI sample controls which are not part of an official SAP shipment make use of UI5 components which we do not guarantee to ship with our product. In orders words internal code coming with Design Studio is used that is not released for public usage.
It is always a risk to do this and we cannot guarantee that we stay compatible. And furthermore we do not test this kind of usage.

1.6 SP 2

http://localhost:63105/aad/resources/~20160613172221~/sap/suite/ui/commons/library.js
/*!
 *
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * (c) Copyright 2009-2015 SAP SE. All rights reserved
 *
 */
jQuery.sap.declare("sap.suite.ui.commons.library");
jQuery.sap.require("sap.ui.core.Core");
jQuery.sap.require("sap.ui.core.library");
=> jQuery.sap.require("sap.suite.ui.microchart.library");
jQuery.sap.require("sap.m.library");
sap.ui.getCore().initLibrary({


library.js exists but is nt loaded from here: (local mode)
com.sap.suite.suite-ui-microchart_1.34.12.jar\META-INF\resources\sap\suite\ui\microchart\library.js

404 http://localhost:63105/aad/resources/~20160613172221~/sap/suite/ui/microchart/library.js"

Actually we need to upgrade to SP2 asap, because it fixes an issue with integrated planning which we need for a different project on BI platform. Is there any option to adapt sdkpackage in a way that it can be used with SP2 already?

**Comment by KarolKalisz** [comment]
it would require to include this code in SDK package to get this running again. I will check in next 2 days how much effort it is.

**Comment by KarolKalisz** [comment]
we will keep this issue for some while and close in few weeks once SP2 P1 is used and someone of you will confirm the corrections.

correction commented by #129

**Comment by KarolKalisz** [comment]
mas far I know fix on DS side is already released. can someone confirm that we close this?

**Comment by MartinPankraz** [comment]
Hi everyone,

I included some MicroBulletCharts with the KpiTile component today myself and corrected the coding accordingly for the new sapui5 library. As of the DS1.6 SP2 you can now use all of the MicroChart types once our new SCN repos built is published.

@KarolKalisz : The neccessary changes got me a little confused because during my first tests the new microchart lib was already loaded. Some further testing showed that this is not always the case. To be 100% sure I updated your sapui5 include code. Please check if that makes sense to you going forward.

Kind regards
Martin
