### ISSUE TITLE
Microcharts are failing with Design Studio 1.6 SP 2

### ISSUE THREAD

**Issue by engelchrisi** [org-scn-design-studio-community/sdkpackage#129]
DS 1.6 SP 2 contains a new UI5 library which contains a new microchart component. The web server manifest did not reference this new component and therefore its files could not be loaded.

Solution: Install Design Studio 1.6 SP 2 Patch 1 as soon as it is  available.

**Comment by EviWi** [comment]
this refers to issue #127

**Comment by engelchrisi** [comment]
1.6 SP 2 Patch 1 will be released most likely in CW 27. 
You can find the schedule of Design Studio releases and SPs in following note:
http://service.sap.com/sap/support/notes/1760372

**Comment by KarolKalisz** [comment]
there is one more "issue" (it can be also called redesign) with micro charts in SP2.

in regards to issue #127 we have got conversation with design studio support. the issue #127 will be corrected in patch 1, SP2 - there will be no correction in the community package as workaround.

Design Change in UI5 version included in SP2.

SP2 is in background. There are 2 versions - chart is in Size S.
on the left you can see the version with some CSS (you need to attach "kpiBulletChart" CSS class to your chart). this CSS is moving the chart up by 15px, and hidding the numbers.

Reason: redesign in UIf, obviously charts in size S are minimum 70 px high, so on right side you can see that the chart is there, but in a size which makes it invisible in small areas (here: height = 25px)

.kpiBulletChart div.scn-pack-BulletMicroChart .sapSuiteBMCContent.S {
      top: -15px;
}
 
.kpiBulletChart div.scn-pack-BulletMicroChart .sapMLabel.sapMLabelMaxWidth.sapMLabelNoText.sapUiSelectable {
      display: none;
} 

![micro_1 6sp2](https://cloud.githubusercontent.com/assets/7816449/16337871/f53ecd14-3a18-11e6-9fad-41498a86b524.PNG)

there is an option to use the size XS or adjust the CSS.
hope this helps other, if not comment here.

we will keep this issue for some while and close in few weeks once SP2 P1 is used and someone of you will confirm the corrections.

Karol

**Comment by iSeemey** [comment]
Hie Karol
Can somebody contact you privately or onnly through this channel?

Regards
Steve

**Comment by KarolKalisz** [comment]
Hi,

as far I know a patch has been released and this issue is already fixed in 1.6 release.
can someone confirm (if you tried already)? if not, I will setup it on my own and check.

@iSeemey we can use also SCN for private comm. let me know your scn id, I will follow you and then you can contact me.

Karol

**Comment by MartinPankraz** [comment]
Hi everyone,

I included some MicroBulletCharts with the KpiTile component today myself and corrected the coding accordingly for the new sapui5 library. As of the DS1.6 SP2 you can now use all of the MicroChart types once our new SCN repos built is published.

Kind regards
Martin
