### ISSUE TITLE
Rebuild Preview

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#133]
Hey guys :)

Hope you're doing well !
I can't rebuild the feature due to a java issue with "2 - Build Docu" ... Can someone update the preview version ?

Thanks in advance.

PS: It's not really urgent though.

**Comment by entmike** [comment]
Hey Franck,

If I knew how I would however none of my components are generated with the Java app. Let's see if Karol is around otherwise I can try later.

**Comment by franckblais** [comment]
What's your issue exactly ? the specifications are not taken in account when you build ?

**Comment by KarolKalisz** [comment]
Hi Franck,

for the "2: Docu Build" you need once to import the project in eclipse
C:\DEV\community.sdkpackage\tools\tools.html.generator

then it will be complied and corresponding classes will be created. After this step, the batch file will work (should).

what it does?
as first step, it is generating the  contribution files for components which are based on specs and then it is parsinf all contribution files to generate the help for web page.

**Comment by franckblais** [comment]
Thx Karol ! You even referenced the commits associated to it :)
