### ISSUE TITLE
SDK Data Iterator item could not be generated

### ISSUE THREAD

**Issue by JonasDuclos** [org-scn-design-studio-community/sdkpackage#137]
Hello,

Can i have a feedback of some people using the item DataIterator from the SDK Community ? Is it working on BI Platform 1.6 SP02 ?

In my side, i'm not able to load this item when i launch the application from BI Platform, i have this issue :

Capture.JPG
![image](https://cloud.githubusercontent.com/assets/20657788/17129850/c307742a-5315-11e6-8886-89eecb82e3e1.png)

SDK is installed on the BI Platform, like on my client

![image](https://cloud.githubusercontent.com/assets/20657788/17129843/b6d14366-5315-11e6-8443-a1aeb81b7248.png)

No issue if i launch the application in local mode with a Design Studio 1.6 SP02 too.

If someone has an idea or a feedback on this item, thank you !

Best Regards, 
Jonas.

**Comment by entmike** [comment]
I am currently not running 1.6 SP2 client so I cannot readily test at the office.  I'll try to remember to do this in a VM later though.

**Comment by KarolKalisz** [comment]
this looks for me like the platform was not restarted after the installation.

**Comment by KarolKalisz** [comment]
closing as no more comments since few months.
