### ISSUE TITLE
Script Editor gets empty when using within Object

### ISSUE THREAD

**Issue by philippgriesser** [org-scn-design-studio-community/sdkpackage#141]
Hi there.

I implemented a Design Studio SDK-Extension and come up against a problem with the maintainance of a specific property within the Design Studio (Design Time).

I wanna change the existing script function but after clicking on the Button (...)

![1](https://cloud.githubusercontent.com/assets/21103178/17773548/568ae272-654f-11e6-9d9d-8383388b68e0.png)

I am getting the script editor which is **empty**. That means the already existing function does not appear in the script Editor anymore.

![2](https://cloud.githubusercontent.com/assets/21103178/17773675/c577de74-654f-11e6-90bf-2b9889a0080d.png)

This problem only exists when I use the script-property within an object - when using the same property as a standalone property this problem does not exists.

For me this seams to be a problem in the Standard SDK-Kernel - may anyone check this issue and let me know if there is a solution for it?

Here are the objects I am using in SDK:

component.xml

![3](https://cloud.githubusercontent.com/assets/21103178/17776167/a67f39c0-655b-11e6-91be-d23e70495f3c.png)

component.js

![4](https://cloud.githubusercontent.com/assets/21103178/17776267/06f5659a-655c-11e6-87dc-ae6a421d052d.png)

Txs, Phil

**Comment by MartinPankraz** [comment]
Hi Phil.

According to SAP it is not possible what you are trying to do. Check [https://scn.sap.com/community/businessobjects-design-studio/blog/2015/11/19/whats-new-in-design-studio-16-sdk](url) 
There it say: 

> You can nest all property types into an Object property, except data-bound properties and ScriptTexts. But you can could nest properties of type Object into others, producing a deep structure.

Apart from that this issue page is targeted towards problems related to our repository and not for questions regarding the product itself. Please use SCN next time.

Kind regards
Martin
