### ISSUE TITLE
Failed to retrieve MIME object 

### ISSUE THREAD

**Issue by VijayaKumarKumar** [org-scn-design-studio-community/sdkpackage#146]
Hi all,

Actually I am new this community space and trying to explore on the Design Studio Extensions Available.
I have cloned the latest master source files to a zip file and extracted.
In Eclipse Environment I have set the target platform Design Studio and also linked to sdk.xsd in the preferences. I have imported the extracted project content which was download from Github and tried running it. The design studio client tool has opened up and the standard components are working when drag and drop, but with the custom components available in the downloaded content at Github... I am unable to drag and drop ... In the error log it says "Failed to retrieve MIME Object sdk_include/org.scn.community.shared/os/viz-modules/SDKCore.js"... 

Could you please help me in understanding what changes need to be done in order to run the custom components using the source files downloaded... 

With Stable Version downloaded, the components are working fine... but interested to know what it takes to run using the source files via Eclipse environment 

Hope I am clear on the above stated... Looking forward for your earliest and valuable help 

Thank You
Vijay

**Comment by KarolKalisz** [comment]
Hi,

you need to import eclipse projects from all modules, basics, databound AND shared as we make reuse between those modules. If you open only one module in Eclipse, the other are not accessible.

can you try?

Karol

**Comment by VijayaKumarKumar** [comment]
Hi Karol,

Regret the delay in response... Could able to access it after importing all the projects...

Thank You for your response 

Vijay
