### ISSUE TITLE
Request for M mode version of Toggle Button

### ISSUE THREAD

**Issue by guymonlh** [org-scn-design-studio-community/sdkpackage#155]
Is it possible to add the Toggle Button to the M mode component offering in the near future?  We would like to convert our Design Studio applications to M mode but rely heavily on this component and I'm just not seeing anything that has the same functionality in the current component offerings in M mode.  Thank you for considering this request.

**Comment by MartinPankraz** [comment]
Hi guymonlh,

The switch component is now shipped with the DesignStudio standard. Maybe you can achieve what you want using that one? If you are still interested in moving the toggle button to m mode let me know. I will implement it over the weekend then.

Kind regards
Martin

**Comment by guymonlh** [comment]
Hi Martin
  Thank you for offering to implement the toggle button in M mode but if it is now standard, I will use the standard component instead.
Thanks!
Lori
