### ISSUE TITLE
totally new to Design Studio - some help please to install SDK components

### ISSUE THREAD

**Issue by sapripan** [org-scn-design-studio-community/sdkpackage#158]
Hello,

I'm starting with SAP Design Studio (1.6) .  I must create a dashboard, and I would like to use a component I've seen from Mike Howles (like-fiori tile).
I would like to browse the SDK components to add some in my software, but it is not working and on the multiple pages that describe the components I can't find the information. 

Tools -> Install Extensions to Design Studio 
I pressed on the "archive" button and installed the .zip file org.scn.community.sdk.package_stable.zip

But, I have an error message repeating  : 
plug in : com.sap.ip.bi.zen
Failed to retrieve SAP assertion ticket

```
org.apache.axis2.AxisFault: getSAPAssertionTicket The exception is of a known origin. (Error: N/A 99998)

```

also, when I try to add the component KPI Tile 2.0, I have the mousewheel turning endlessly, any idea ? 

thank you for your help and sorry for my ignorance...

sapripan

**Comment by sarahmaas** [comment]
I have the same problem with KPI Tile 2.0. I tried opening the examples as well and found that they were created in a newer version of 1.6 than what I have.

![image](https://cloud.githubusercontent.com/assets/11710032/24123550/eb66ad40-0d8d-11e7-97b2-52b25fe8639b.png)
