### ISSUE TITLE
Choropleth Map Extension in Design Studio

### ISSUE THREAD

**Issue by saritaagrawal59** [org-scn-design-studio-community/sdkpackage#162]
Hi Experts,

I have installed Geo Visualization extension in my Design studio SP03 and I am able to create and run it locally. I tried deploying that plugin on BO platform . But even after deployment of plugin, I am getting the same error and not able to see the Choropleth Map on BO launchpad.

Thanks
Sarita Agrawal

**Comment by franckblais** [comment]
Hi,

What's your error exactly ? Have you looked at the logs ?
Can you give us more information ?

I don,t quite understand though: it's working in local mode, not on the plateform and you have the "same" error as what ?

**Comment by saritaagrawal59** [comment]
I was getting ""ITEM" of type "ORG_SCN_COMMUNITY_DATABOUND_CHOROPLETH" could not be generated" error.
But now the error is resolved by deploying the correct file on server.
