### ISSUE TITLE
Loosing CMS Session with BO-Server 4.2

### ISSUE THREAD

**Issue by Voltoviper** [org-scn-design-studio-community/sdkpackage#170]
Hi, 

first of all thanks for this nice AddOn!!!

Since the Installation of this AddOn we are loosing the CMS Session for the unx Universe partially. Sometimes after half an hour. sometimes after 4 hours. Do you have an idea? 

Technical Data:
Installed AddOn Version: 3.0.0.201706221413
Design Studio Version: Release 1.6 SP3 Patch 1
BO-Server 4.2
Other plugins: Graphomate

Greetings from Germany!

**Comment by MartinPankraz** [comment]
Hi Voltoviper,

That sounds weird. I cannot think of any reason why the installation of the DesignStudio SDK extension should interfere with your BO sessions. The whole SDK mechanism is supported by SAP. Are you absolutely sure the problem started with the server deployment of the SDK components?

Another thing I would recommend to check is if the BO-Server version 4.2 is supposed to be compatibile with DS 1.6 SP3.

Apart from that I am afraid you will have to open a ticket with SAP support.

Kind regards
Martin
