### ISSUE TITLE
Adding Multilevel Dropdown

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#19]
Hi !

I managed to commit my extension on the repo. I took the liberty to create a "Discution" label, as we could use "Issues" to discuss some topics.

As per example, the code is not finished yet, and needs some fixes. I'll let you know.

Just let me know if you think it's a bad idea (either integrating my ext now or the discution label ;) )

**Comment by org-scn-design-studio-community** [comment]
very good idea.. lets do the open discussions then here.
