### ISSUE TITLE
Method to install the online composition

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#21]
Hello Karol,

Nice article and composition. This is really an awesome work (at least by judging the screenshots, I am not able to test it now).
Although, I had troubles to understand how to install it.

Of course, one have to install the SDK package and DS 1.4, but how to use the online composition ?
I propose to add a detailed description on each steps in the blog entry:
 - Install DS 1.4
 - Open DS, install the Community package (http://scn.sap.com/community/businessobjects-design-studio/blog/2014/12/10/scn-design-studio-sdk-development-community)
 - Download the online composition (zip archive from Karol's blog page)
 - Go in DS and display your repository folder (Application -> Open repository folder)
 - Extract the archive in this folder
 - Restart Design Studio, open the SCN_ONLINE_COMPOSITION_V1
 - Configure the system ID (check first link)
 - Run and enjoy !

What do you think ?

Have a good day :) I'll test it this evening !

**Comment by KarolKalisz** [comment]
good point Franck, this was for me too obvious as I make those steps every day...
I have actualized the V2 blog.
