### ISSUE TITLE
Incorrect object use in org.scn.community.shared\def_shared\contribution.ztl

### ISSUE THREAD

**Issue by sschau** [org-scn-design-studio-community/sdkpackage#22]
Hi,

at line 93.  Orignial code is

var conditionalFormat = DS_1.getConditionalFormats();

which DS_1 is not a valid object in this scope.  It should be

var conditionalFormat = ds.getConditionalFormats();

Thanks.

**Comment by entmike** [comment]
Thanks for reporting this issue - I've pushed up a correction.
