### ISSUE TITLE
SDN Repo package installation from the archive

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#23]
Hey guys,

Happy new year :)

I tried to install (again, new laptop) the SDN Extension and bumped on an issue. I didn't check it out myself, but I wanted to share it with you before.

I was able to download the archive, add it to DS 1.4. When DS ask for which "package" ( 1.3 or >= 1.4), I couldn't make it work with 1.4, but with 1.3 yes, and actually, it seems that the two of them are inverted.

I am pretty sure I saw a "1.4" somewhere in the extensions in DS after the installation (Yep, in Basics Menu bar and Menu Button).

**Comment by KarolKalisz** [comment]
Franck, which packages have you selected? 
The 1.4 package is containing data sources which are not working on 1.3 release, but this package requires the 1.3 - in other case this does not work.

**Comment by franckblais** [comment]
I am in 1.4 and choose 1.4, failed. If I choose the 1.3 package, it works well !

It is a bit confusing :)

**Comment by KarolKalisz** [comment]
You have to select in 1.4 BOTH packages, as the 1.4 is an extension for 1.3 package. We have made a split for 1.3 users, as the 1.4 contains SDK Data Sources which are not importable in 1.3 release.

does this solve your issue?

**Comment by franckblais** [comment]
Ohh ! I understand now !

I think it does :)

On Wed, Mar 11, 2015 at 12:26 PM, Karol Kalisz <notifications@github.com>
wrote:

> You have to select in 1.4 BOTH packages, as the 1.4 is an extension for
> 1.3 package. We have made a split for 1.3 users, as the 1.4 contains SDK
> Data Sources which are not importable in 1.3 release.
>
> does this solve your issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/23#issuecomment-78299045>
> .
>



-- 
Franck BLAIS
