### ISSUE TITLE
Online Composition - Fragments and Compose not working with some System name

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#24]
Hi all,

Just to say that the fragments and compose are not working if the SAP system name is not "correct".
When I was trying the Online composition, I was not able to use the fragments at all, just because my system was named "BI1 - 7.3". The error was quite straightforward here: the name contains not authorized characters.

Maybe it could be a good idea to find a way to override this limitation and, maybe, rename internally the system to a usable one by the fragments.

**Comment by entmike** [comment]
I noticed also that hypens weren't supported for XSYSTEM.  I had to rename my SAP GUI connection entry and remove the '-' for mine to work.

**Comment by franckblais** [comment]
Had to do the same thing.

**Comment by KarolKalisz** [comment]
I will check this issue.

**Comment by KarolKalisz** [comment]
please check with V2, I have escaped some unallowed characters from system description.
