### ISSUE TITLE
Why did I just fork? I think I need to introduce myself!

### ISSUE THREAD

**Issue by markbainflynet** [org-scn-design-studio-community/sdkpackage#28]
Hello SCN Design Studio community SDK team,

I am looking at starting to contribute to the SDK projects. I am a completely inexperienced with Github, but I am used to other code versioning tools.

I forked the code in an attempt to learn the system. That way I can play around and not worry about breaking things in the main project. Once I am happy with how things work, I'll look into how I interact with the master branch properly (with pull requests etc).

Thanks a lot!
Mark Bain

**Comment by markbainflynet** [comment]
My first question would be.. how on earth do I assign the 'Discussion' label to this issue? :-)

Cheers,
Mark.

**Comment by franckblais** [comment]
Hello and welcome !

You just have to edit and click on the label :)
Even if I used another versionning tool in the past, I realize that I am not too comfortable with GitHub either.
Do not hesitate to share your experience with the fork, even if I suppose Mike and Karol are more experienced.

**Comment by entmike** [comment]
Welcome :)  Glad to see more new folks, the more, the merrier!

**Comment by markbainflynet** [comment]
I poked around for labels (while in edit mode), but couldn't see the option anywhere to add them. I wonder if it is a user rights thing? I will look around even more when I next raise and issue / discussion :-)

I have managed to get my head around Git and GitHub enough to delete my fork.

I have the main repository cloning down to our local Git server, maintaining a 'remote' back to GitHub as an upstream server. This means my colleagues and me can play around with SDK locally as a team, and when we're happy, we can submit it back upstream. All very cool.

Thanks guys,
Mark.

**Comment by franckblais** [comment]
Here, to add the label:
![image](https://cloud.githubusercontent.com/assets/10117707/6442242/2f05741c-c0bc-11e4-8839-75d8d47c28f2.png) and then I just clicked on the one :)
![image](https://cloud.githubusercontent.com/assets/10117707/6442244/3884bc78-c0bc-11e4-994c-26027ea35414.png)

**Comment by entmike** [comment]
Hey Mark,

I'll see if we can open up labels to all participants.  Also after you get your feet wet in the fork you have and want to do your first commit to this repository, we can for sure get you set up as a collaborator.  We let folks build up a little familiarity and confidence first since (as you've already seen) there's .bat files and a bunch of other craziness going on behind the scenes :)

**Comment by markbainflynet** [comment]
Thanks guts for the feedback. I think we can close this discussion now? Keep things nice and tidy.

Cheers,
Mark.
