### ISSUE TITLE
Executing script/1-prepare_build.cmd as a part of the debug / run workflow

### ISSUE THREAD

**Issue by markbainflynet** [org-scn-design-studio-community/sdkpackage#30]
Hello guys,

Is it possible to configure Eclipse so that the *script/1-prepare_build.cmd* command is executed automatically when you debug / run your Design Studio SDK solution? At the moment, I have to create an external shortcut or keep a command window open, and remember to do it manually.

Sorry if I am coming across as stupid. We are accomplished developers, but not in the Eclipse environment :blush:

Cheers,
Mark.

**Comment by markbainflynet** [comment]
...and on a side note, I definitely don't have the option of adding *labels*.

**Comment by entmike** [comment]
Hey Mark,

You only have to bother with running that script when you make changes to your contribution.xml or .ztl files.

As for executing the batch in Eclipse, I do similar for some Grunt tasks that are in a .bat file, just use the External Run configurations (The green play button that has a little red toolbox next to it) and set up a config to run the .bat file.

Again, unless you are frequently adding in properties and BIAL methods to your XML and ZTL files, you don't have to run every time before launching DS.  JS changes don't need the .bat file to be run.

**Comment by markbainflynet** [comment]
Hi Mike,

Thanks for that. I am making lots of changes in the ZTL files at the moment :smile: 

Pointing out the External Run configurations has made it easier.

Thanks a lot,
Mark.
