### ISSUE TITLE
Our First Contribution - Questions - Etiquette - Debugger

### ISSUE THREAD

**Issue by markbainflynet** [org-scn-design-studio-community/sdkpackage#31]
Hello guys,

We here at Flynet have been using the *Debugger* to help build our custom data source. It has been of great help. Thanks! However, we have had to make modifications for it to work. We of course want to offer these changes to the community project.

We have several concerns. None of us have ever contributed to an open source project, nor used GitHub to any great extent.

We are not sure how you are meant to raise these kind of questions and queries. We don't want to upset anyone, and don't want to come across as anything less than extremely grateful for everyone's work :smile: 

**The *inspectNow()* and *inspectZtl()* Functions**
First of all, when we look at the debugger code, we are not sure what *inspectNow()* is trying to offer :smile: 

There seems to be overlap between *inspectNow()* and *inspectZtl()*. A differentiator seems to be that *InspectNow()* allows the passing in of a comment, but the code seems somewhat unfinished. We have updated the function so that it works, allowing you to add a comment to the console log. But it just seems a little... weird. There seems to be a lot of duplication between *inspectNow()* and *inspectZtl()*.

Would it not be better just to update *inspectZtl()* to allow the addition of comments?

**Inconsistent Parameter Type for *Owner* / *thisValue* Object**
This may be a gap in our Java / JavaScript / Rhino / ZTL knowledge. We are .NET coders after all!

Sometimes the inspect functions have the owner (thisValue) parameter passed in as a *String*, *Object* or Design Studio SDK *Component*. Coming from a strictly typed background (.NET), it seems to us that it should always be type *Component*. We have tried that in our local repository, and it works fine.

Is there any reason why it shouldn't be *Component*, and that sometimes *String* and *Object* are better choices? Why would this be the case? The fact that *String* works at all is surprising, but that is probably JavaScript / Rhino for you!

**Owner *getOwner()* Function**
The debugger code attempts to call a *thisValue.getOwner()* function, and then access the function *getItemType()* on the returned object. This fails as it is *undefined*. Is this *getOwner()* function a feature of the Design Studio *Component* class? Where would we find detailed information on the *Component* class?

In our local repository we had to comment out the *getOwner()* section of code for it not to throw an exception.

We also made some changes to the type detection loops for *Owner* and *local* objects, as the existing code didn't work :smile: 

So, lots of questions. Sorry about that! We're just not sure how we are meant to approach these kind of things.

Thanks a lot,
Mark.

**Comment by markbainflynet** [comment]
Hi guys,

Does anyone have any feedback? :smile: 

Or should I just submit a pull request?

Cheers,
Mark.

**Comment by entmike** [comment]
Hey Mark,

I was kinda waiting to see if Karol had an opinion, as this one was all Karol.  He may still be out of the office but if you've got a good working copy that's working more consistently as you've described, you have my support!  Let's see if Karol responds by end of this week, if not, we can go ahead and incorporate the changes, I do not think he will mind.

**Comment by entmike** [comment]
Hey Mark - I see Karol's active on GitHub this week, will ping him and see if we can get you going.

**Comment by KarolKalisz** [comment]
Hi Mark, I have this week more time, will respond to your thread.

**Comment by KarolKalisz** [comment]
so, first the easy answers without debugging...

The inspectNow() and inspectZtl() Functions

indeed, both are similar.
the inspectZtl() function cannot be used in BIAL scripts, it gets objects as parameters and those can be only passed in ZTL file when calling directly in rhino engine.

the inspectNow() function is a restricted version which allows also calls in any BIAL event, so you can use it eg. for check of global variables.

API:
void inspectNow(optional String comment, optional Component thisValue)
void inspectZtl(Object thisValue, Object locals, Object exception)

basically, the "*Ztl" functions should be not accessible in BIAL, but I have not made them hidden.

Inconsistent Parameter Type for Owner / thisValue Object
This is quite funny topic in JavaScript, basically it does not matter what parameter type is defined in ZTL, you can always access it how you want. The types are only for the XText parser in Design Studio, so when the parameters are unknown for the XText parser, those functions will be not working correctly in BIAL scripts.

But, I have changed the "String" definition to "Object". Initially I was not sure if I can use "Object" there - but looks this is acceptable by XText and Rhino processor. Of course, such methods can be called only from ZTL scripts.

Owner getOwner() Function
Have you checked with newest version? I hope this does not fail any more, if yes, which line?

This came as proposal from Mike on how to figure out the component type. Technically every component in Rhino has the "owner" which is the component in object model, and the type is on this one. W/o this call you cannot know the type of the component. I change the code to be more flexible:

				var owner = thisValue.getOwner();
				
				if(owner) {
					lVariables.push({"date":l.date, "item-type":name, "value":owner.getItemType(), "type":"info"});
					lVariables.push({"date":l.date, "item-name":name, "value":owner.getName(), "type":"info"});
				}

what are your changes?
[...] We also made some changes to the type detection loops for Owner and local objects, as the existing code didn't work :smile: [...]

for me it works so far, but I do not want to claim a "perfect software" solution ;-)

Karol

**Comment by KarolKalisz** [comment]
Mark, all good on this topic?
Karol

**Comment by markbainflynet** [comment]
Yes, thanks Karol.

Sorry, we're in the middle of starting a new development push and I've been distracted :-)

Cheers,
Mark.
