### ISSUE TITLE
Fetch and Merge: Commit what ??

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#33]
Hello guys,

I tried to git fetch and merge this morning, and had a lot of conflicts ... Especially on Contrib XML and ZTL:
> org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
> src/org.scn.community.databound/contribution.xml
> src/org.scn.community.databound/contribution.ztl
> src/org.scn.community.databound/res/MultiLevelDropDown/def/contribution.xml
> src/org.scn.community.databound/res/MultiLevelDropDown/def/contribution.ztl
> src/org.scn.community.datasource/contribution.xml
> src/org.scn.community.datasource/contribution.ztl
> src/org.scn.community.geovis/contribution.xml
> src/org.scn.community.geovis/contribution.ztl
> src/org.scn.community.shared/contribution.ztl
> 	at org.eclipse.jgit.api.MergeCommand.call(MergeCommand.java:406)

I am a bit confused about what I should do ...
I don't understand as well how to see the conflicts. Can you please advise ?

Instead of using GitHub "standard"  plugin, should I use eGit ?

Thanks

**Comment by entmike** [comment]
I really fumble here a lot, too :)  Maybe someone can teach me how to fix, too.  Usually it's with the contribution.xml/ztl files as well.

If I know I've "touched" those files with my own code, I'll make a copy to be sure, and then right-click the conflict files in Eclipse, and pick Replace With and then pick HEAD Revision.  After doing that everywhere you have conflicts, you can usually re-pull the latest, and then you are in sync to Commit.

Again, I am a TOTAL Git newbie so I'm learning as I'm going as well :)

**Comment by franckblais** [comment]
Thanks for the advices ! I'll try that ...
But I didn't made any copies except for my own modifications ... And I did not touch any of the geovis and Shared.

Let's try ... !

**Comment by franckblais** [comment]
By trying to install eGit I broke my Eclipse install ...
I will clone again in a new folder and copy/paste my changes ...
