### ISSUE TITLE
Idea: ChoroPleth

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#35]
Hello,

Just to keep some ideas about enhancing the Choropleth:
 - Set method for feature and label attribute
 - Be able to deactivate the display animation
 - Change dynamically the map content

**Comment by entmike** [comment]
Hey Franck - Item 1 is now done.
For animation you can set animation duration to 0 to disable animations.
Dynamic change of map content may be a challenge.  I locally store the Geo/TopoJSON at design time from APS downloads/user pastes.  I don't currently have a mechanism to change the map at runtime though.  Thoughts?

**Comment by franckblais** [comment]
Changing the map is actually not really necessary, we can think of other
solutions ! I understand the issue.

Thanks for 1 and 2 :)

I will add more things while playing with the maps :)

On Mon, Mar 23, 2015 at 2:50 PM, Mike Howles <notifications@github.com>
wrote:

> Hey Franck - Item 1 is now done.
> For animation you can set animation duration to 0 to disable animations.
> Dynamic change of map content may be a challenge. I locally store the
> Geo/TopoJSON at design time from APS downloads/user pastes. I don't
> currently have a mechanism to change the map at runtime though. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/35#issuecomment-85141784>
> .
>



-- 
Franck BLAIS
