### ISSUE TITLE
2D - Crosstab: add columns when moved

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#36]
Hello !

I found a bug a 2D crosstab: everytime I move the component, a new column is added:
At first:
![image](https://cloud.githubusercontent.com/assets/10117707/6790540/c798533e-d17e-11e4-85b8-1dfbad18b1a5.png)
First move:
![image](https://cloud.githubusercontent.com/assets/10117707/6790545/cf135028-d17e-11e4-9f6d-ca1539247e66.png)
Second Move:
![image](https://cloud.githubusercontent.com/assets/10117707/6790548/d54a2a5c-d17e-11e4-821f-12b43d88a423.png)

**Comment by entmike** [comment]
Well that's annoying, huh?  :)

**Comment by entmike** [comment]
Should be fixed now if you pull down the latest source.

**Comment by franckblais** [comment]
Thanks Mike, I'll test it.

**Comment by franckblais** [comment]
Found another bug with the data selection:
![image](https://cloud.githubusercontent.com/assets/10117707/6804402/a2570a26-d1fa-11e4-8328-45731ae004eb.png)
Cannot select anything :(

Btw, its on a Hana calculation view.

**Comment by anilakkala** [comment]
Hi Franck,

we are facing same Issue for other Standard Design Studio Components as well while we doing data selection, we found that its resolution Issue

Workaround was, Minimize the window as small as possible and close it, again click on the data selection then you will see the prompts, use "TAB" to go near "OK" button

**Comment by franckblais** [comment]
Hi Anil,

Thank you ! I'll test that :)
