### ISSUE TITLE
SDK Community package Installation from the Online Repo not working

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#37]
Good Morning !

The stable and preview URL in the Blog to install the Package are not working

> Online Repository
> stable: http://org-scn-design-studio-community.github.io/sdkinstall/releases/stable
> preview: http://org-scn-design-studio-community.github.io/sdkinstall/releases/preview

Error 404 :)

**Comment by entmike** [comment]
These links are for the DS client installer NOT browser.

**Comment by franckblais** [comment]
Even though, it is not working by copy/pasting the url in DS for me. Does it work for you ?

**Comment by entmike** [comment]
Yes - just checked.

On Tue, Mar 24, 2015 at 9:27 AM, franckblais <notifications@github.com>
wrote:

> Even though, it is not working by copy/pasting the url in DS for me. Does
> it work for you ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/37#issuecomment-85522844>
> .
>



-- 
Mike Howles

**Comment by franckblais** [comment]
Strange, I'll test again !

**Comment by entmike** [comment]
If you are wanting to test my more recent corrections, you'll have to launch from Eclipse, not the feature bundle.  I'll update that today.
