### ISSUE TITLE
Range Slider - Ticks not aligned with indicator

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#39]
![image](https://cloud.githubusercontent.com/assets/10117707/6897389/64c610e6-d6c1-11e4-9a77-04699c671ea7.png)

Basics - Range Slider.
Issue happens on other slider as well. Logic since al are derived from Sap.ui.commons.slilder.

**Comment by KarolKalisz** [comment]
Franck, this can happen when the MIN, MAX values with SMALL STEP WIDTH and the TOTAL UNITS are not in sync, eg. like below:

min: 0
max 100
small step width: 10
total units != 10, eg. 11

please check in your scenario, all properties can be set also via ZTL.
![ticks](https://cloud.githubusercontent.com/assets/7816449/7031059/3f45d122-dd69-11e4-9dbb-1414aeae0b05.PNG)
