### ISSUE TITLE
Unexpected behaviour of Client Information Component

### ISSUE THREAD

**Issue by PatrickGodwin** [org-scn-design-studio-community/sdkpackage#40]
During development of dashboards including the Client Information Component I have notice the follow behaviour which is unexpected:

1) Client Information is not initialised on application start up. Calls to methods exposed by the component during Application On Startup event return a generic script error. After this, if the Client Information methods are accessed by other events (such as onClick()) they perform as expected.

2) Post startup, after successful use of methods exposed by Client Information Component, if application is reverted to the initial state using State.backToStart() or State.backOneStep() the behaviour exhibited in 1) occurs; however the component is unresponsive to all subsequent events.

I am unable to find a way of attaching a sample app to demonstrate, however here are the steps to reproduce:

1) Create a new blank app
2) Set Behaviour > Maximum Number of Undo Steps to 10
3) Add three buttons (BUTTON_1, BUTTON_2, BUTTON_3)
4) Add a Client Information component (CLIENTINFORMATION_1)
5) Add the following code to Application On Startup Event 
 TEXT_1.setText("Height: " + CLIENTINFORMATION_1.getOwnHeight());
6) Add the following code to BUTTON_1
TEXT_1.setText("Height: " + CLIENTINFORMATION_1.getOwnHeight());
7) Add the following code to BUTTON_2
State.backToStart();
8) Add the following code to BUTTON_3
if (State.isBackOneStepAvailable()) {
	State.backOneStep();
	BUTTON_3.onClick();
}
9) Run the application, noting error messages.

**Comment by KarolKalisz** [comment]
please check if this is better now. there is a new method "reload()" which must be called after such actions.

btw. usage of this component in onStartup() is not possible as this component requires a roundtrip to get the information.
