### ISSUE TITLE
Border or Space in Marimekko Chart

### ISSUE THREAD

**Issue by anilakkala** [org-scn-design-studio-community/sdkpackage#41]
Hi Mike,
 
Thanks for providing wonderful Marimekko Chart.

This chart was perfectly suited for one of our clients requirements, but if it had one more enhancement then it would be wonderful at least for us.
 
Is it possible to have a small gap between each Colum or a thick border like below in Marimekko Chart

Orginal
![mc](https://cloud.githubusercontent.com/assets/11783128/6980062/1d52c40a-da1f-11e4-9a01-598f6f9669ef.png)
 
Option - 1
![mc2](https://cloud.githubusercontent.com/assets/11783128/6980067/2323c4b0-da1f-11e4-8b79-1298dc26ef51.png)

 Option - 2
![mc3](https://cloud.githubusercontent.com/assets/11783128/6980072/2b32a9be-da1f-11e4-8562-d7df588a5e05.png)

**Comment by entmike** [comment]
Still need this?  Playing catch-up on issues :)

**Comment by KarolKalisz** [comment]
Hi,

I have made it to close this issue, and also try out how to extend controls from MIke ;-)
but we will probably need some "point"-rating for such requests... e.g. make a change if really more members will request it.

there is a new property "Border Space" in "Cosmetics" category. Default is 0.

Karol

**Comment by KarolKalisz** [comment]
Hi,

I have made it to close this issue, and also try out how to extend controls from MIke ;-)
but we will probably need some "point"-rating for such requests... e.g. make a change if really more members will request it.

there is a new property "Border Space" in "Cosmetics" category. Default is 0.

Karol
