### ISSUE TITLE
Add date format string

### ISSUE THREAD

**Issue by HenryTaylor** [org-scn-design-studio-community/sdkpackage#45]
Given Design Studio's treatment of dates as "Mon DD, YYYY", it'd be helpful if the .format() method allowed a format string of that form, so that one could get back a date string that is readily usable for passing to Data Source query prompts, etc.

**Comment by KarolKalisz** [comment]
Hi Henry,

there is new method in REALDATE - formatWithMask(). check if this solves your topic.
The change is done in PREVIEW release, not yet on STABLE.

Karol

**Comment by HenryTaylor** [comment]
I installed the preview version of the package, but it doesn’t appear to be installing it’s objects.  I ran into this the other day when I tried to install the 1.4 stable package.  I had no objects.  I had to go to the 1.3 stable to get the objects.  This even though my version is 1.4 (Version 14.0.3).  Not sure what’s going on.

Henry Taylor
Agri Stats
260-407-2715
htaylor@agristats.com
