### ISSUE TITLE
Gauge needle Spins while initial page load. 

### ISSUE THREAD

**Issue by RaoVedula** [org-scn-design-studio-community/sdkpackage#46]
My Value in Gauge is showing up right. but my Needle rotates almost 350 deg for a value of 72 //////////........ var val=DS_2.getData("00O2SNODRJTRZENZHDITULUC8",}).value; ///////// .........GAUGE_1.setIndicatorValue(val);  ///////.......GAUGE_1.setShowedValue(Convert.floatToString(val));

 

within the Dashboard I browse to another screen and come back,  the needle will show correct value. But initially when I start the Dashboard the needle behaves pretty strange..

**Comment by KarolKalisz** [comment]
Hi Rao,

I could reproduce - somehow the value is doubled when changing the visibility.
I try to look at this next week.

Karol

**Comment by RaoVedula** [comment]
Thanks Karol.
you are right my needle is stopping at double the amount.

**Comment by KarolKalisz** [comment]
Hi Rao,

I have fixed this issue, please check the "preview" release - if you confirm this fix, I make it as stable.

Karol

**Comment by RaoVedula** [comment]
Karol,
It is working Great !
Thanks a lot.
I owe you one Blue Label :)
