### ISSUE TITLE
Choropleth does not render APS, map cannot be selected.

### ISSUE THREAD

**Issue by KarolKalisz** [org-scn-design-studio-community/sdkpackage#49]
insert choropleth, you see only a text that something needs to be done in the properties, but there are no properties.

**Comment by entmike** [comment]
This worked for me when checking just now in latest Git pull:

![image](https://cloud.githubusercontent.com/assets/174348/7158133/741b072c-e33c-11e4-98c1-4ebe22c97ae5.png)

**Comment by KarolKalisz** [comment]
works
