### ISSUE TITLE
Real Date .formatWithMask and .rollWeeks not working correctly

### ISSUE THREAD

**Issue by HenryTaylor** [org-scn-design-studio-community/sdkpackage#50]
I've placed the following code into the Select event of a Date Field object:

gv_endDate = DATEFIELD_1.getDate();

REALDATE_1.initializeWithInternalDate(gv_endDate);

var endDate = REALDATE_1.formatWithMask("mmm dd, yyyy");
APPLICATION.createInfoMessage(endDate);

REALDATE_1.rollWeeks(-10);

var startDate = REALDATE_1.formatWithMask("mmm dd, yyyy");
APPLICATION.createInfoMessage(startDate);

I am selecting April 4th, 2015 from the Date Field.  endDate ought to read "Apr 04, 2015", but it reads "Apr 03, 2015".  One day off.

startDate ought to read "Jan 24, 2015" (I believe), due to the .rollWeeks(-10), but it is also returning "Apr 03, 2015", same as endDate.

**Comment by KarolKalisz** [comment]
now it works, actually the formatWithMarsk function was only affected. it has not taken the correct date and created always the current day-date.
