### ISSUE TITLE
Dynamic csv Data source does not work for me

### ISSUE THREAD

**Issue by Fabien33** [org-scn-design-studio-community/sdkpackage#51]
Hi all,

I'm trying to use the custom datasource Dynamic csv but it does not work. I enter as a url  http://mikehowles.com/data2.csv for the CSV file propoerties (the link is fine). Then I add a simple chart and I select the csv as a data as a datasource but it said "no Data available" ? It does the same with the 2D Crosstable ? What am I doing wrong here ?

![capture](https://cloud.githubusercontent.com/assets/12234596/7454125/03f7991c-f271-11e4-8851-f6ce37b7fbc7.jpg)

Thank you

Fabien

**Comment by MartinPankraz** [comment]
Hi Fabien,

A little late but I'd like to answer anyway for later reference. I just tested the community csv and the BYO datasource with a standard chart and the community's UI5Table. Everything went good. But you need to make sure your CSV follows a certain structure. Let me give you a working example:

ID;EUR;EUR;EUR
01;-48,72;0,00;-48,72
02;5.356.373,81;2.121.455,84;1.170.743,69
03;49.560.839,60;27.255.315,52;6.203.306,37
04;1.875.069,85;1.551.731,81;-111.522,43
Result;56.779.818,62;31.226.364,12;7.325.886,09

Paste that into a CSV file and load it using our custom datasource. You might also want to check the properties "Has Header*". Make sure you have the latest release of our SDK extensions of course. There was a bug recently when upgrading to version 3.0 for DesignStudio 1.6.

Please note that the standard crosstab cannot be used with SDK data sources.

Regards
Martin
