### ISSUE TITLE
BIP Installation of Preview / Stable 2.0 version

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#53]
I tried to deploy the Preview (and the stable) 2.0 version through "Tools -> Platform extensions" and received an error message for Shared:

> !ENTRY com.sap.ip.bi.zen.ui 4 0 2015-06-17 14:15:15.776
> !MESSAGE One or more extensions failed to install
> !STACK 0
> com.sap.ip.bi.zen.connectivity.ConnectivityException: Failed to access plugin JAR file of extension "Design Studio SCN Community Shared" (id: org.scn.community.shared)
	at com.sap.ip.bi.zen.backends.bip.BiPlatformSystem.deployExtensions(BiPlatformSystem.java:2303)
	at com.sap.ip.bi.zen.ui.internal.dialogs.sdk.PlatformExtensionsDialog.installExtensions(PlatformExtensionsDialog.java:278) ...

I'll try to debug it but, in the mean time, if you have a clue :)

Platform: BIP 4.1 SP5
DS 1.5

**Comment by franckblais** [comment]
Just following up.

I noticed something "Stange":
![image](https://cloud.githubusercontent.com/assets/10117707/8210237/0cfc7bf0-14df-11e5-9a68-369bcee1305f.png)
As you can see, all plugins are in a jar file, except for Shared, just after the installation in DS 1.5.

Even weirder:
* Copying / creating a jar Shared file does not fix the Platform installation issue
 * Deleting the Shared folder and leaving the jar works on local (as expected), but the Shared components are not deployable on BIP anymore

**Comment by entmike** [comment]
I've not downloaded the newest sources yet, however I'm going to guess that
Karol may have accidentally left 'Unpack the plug-in archive after the
installation' checked in the feature project.  I know that if you
accidentally do this, it will run in client mode but will not deploy to
server.  Also, you'll have unpacked jars in your plugins directory as
you've shown above.

On Wed, Jun 17, 2015 at 9:55 AM, franckblais <notifications@github.com>
wrote:

> Just following up.
>
> I noticed something "Stange":
> [image: image]
> <https://cloud.githubusercontent.com/assets/10117707/8210237/0cfc7bf0-14df-11e5-9a68-369bcee1305f.png>
> As you can see, all plugins are in a jar file, except for Shared, just
> after the installation in DS 1.5.
>
> Even weirder:
>
>    - Copying / creating a jar Shared file does not fix the Platform
>    installation issue
>       - Deleting the Shared folder and leaving the jar works on local (as
>       expected), but the Shared components are not deployable on BIP anymore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/53#issuecomment-112831385>
> .
>



-- 
Mike Howles

**Comment by franckblais** [comment]
Mmmhhh,

I check the feature.xml in the archive (same behaviour with archive/update site)
![image](https://cloud.githubusercontent.com/assets/10117707/8210932/6b2b225a-14e2-11e5-8d8e-5e28a750aa99.png)
Seems it's unchecked.

**Comment by entmike** [comment]
Interesting!  I'm out of ideas at the moment then...

On Wed, Jun 17, 2015 at 10:17 AM, franckblais <notifications@github.com>
wrote:

> Mmmhhh,
>
> I check the feature.xml in the archive (same behaviour with archive/update
> site)
> [image: image]
> <https://cloud.githubusercontent.com/assets/10117707/8210932/6b2b225a-14e2-11e5-8d8e-5e28a750aa99.png>
> Seems it's unchecked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/53#issuecomment-112840583>
> .
>



-- 
Mike Howles

**Comment by franckblais** [comment]
It's too bad: seemed tho be the issue !

**Comment by franckblais** [comment]
So, yes, the Shared component is installed decompressed:
![image](https://cloud.githubusercontent.com/assets/10117707/8286876/47eeac0c-18da-11e5-9532-2f4caf45e57a.png)
As we can see, when installing, the .jar is missing (but it's working in local).

I searched a bit on SCN but no real answer could be found, and I am too newb to find out something in the xml files ...

I tried to clean my DS and reinstall, same error.

**Comment by franckblais** [comment]
Thanks Mike !

You're right ... Checked in Datasource. Have you rebuild the project ?
Thanks again ! :)

**Comment by KarolKalisz** [comment]
fixed already by Mike. closing it.
