### ISSUE TITLE
Bug:  DS 1.5 Fiori components display error when dragged onto canvas

### ISSUE THREAD

**Issue by mrbensan** [org-scn-design-studio-community/sdkpackage#58]
When a Fiori App Header, Fiori Bar, Fiori Toolbar and Launchpad component are dragged and dropped onto the design canvas, the following error message is displayed:

![fioricomponenterror](https://cloud.githubusercontent.com/assets/6189517/9654148/1f25a8ea-526c-11e5-80a8-fa70f8843060.png)

**Comment by org-scn-design-studio-community** [comment]
looks like is corrected already by Mike, release of today does not have this bug any more
