### ISSUE TITLE
OPENURLINPLACE

### ISSUE THREAD

**Issue by jmarchal** [org-scn-design-studio-community/sdkpackage#61]
Hi Community,

For one of our client, we juste upgrade to the latest version of Design Studio 1.5 SP1 Patch 1. And everything seems to work fine exept for OPENURLINPLACE. When clicking on a Button which apply a OPENURLINPLACE, a new launchpad is opened inside the actual launchpad. But OPENWINDOWPOST is working.

Any idea ?

SAP BUSINESS OBJECT 4.1 SP6 Patch 2
SAP DESIGN STUDIO 1.5 SP1 Patch 1

Thanks for your help!

![image](https://cloud.githubusercontent.com/assets/15015843/10339548/edee78d2-6cd9-11e5-8208-a64538c622ff.png)

**Comment by jmarchal** [comment]
The issue was google Chrome related and fixed after a restart and cleaning of the browser. Sorry.

**Comment by KarolKalisz** [comment]
ok. good to hear that it get solved.
