### ISSUE TITLE
UI5 Table Scrollbar missing, if header column widths too long

### ISSUE THREAD

**Issue by BjoernKuhlmann** [org-scn-design-studio-community/sdkpackage#62]
If column width is e.g. set to 200px each and table has 4 dimensions, but component has only 450px width the row is diplayed wrong.

Please include a horizontal scrollbar instead.
![ui5_table_issue](https://cloud.githubusercontent.com/assets/15194599/10576678/5fa7d4f2-7665-11e5-9adb-1cd80369441a.png)

**Comment by KarolKalisz** [comment]
Hi Björn,

I have taken some hours of my time to look at this. And, 
* this is only in IE
* this is happening when the size is smaller than the number of columns which are "fixed"
* the number of fixed columns can be changed in the meantime in properties.

so, with this it can be handled by designer.
my tries to make some calculations for this scenario were failing with more and more use cases.

Karol
