### ISSUE TITLE
Rebuild Stable and Preview

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#64]
Hello,

Could you rebuild the preview and stable version ?
Thank you.

**Comment by EviWi** [comment]
Hello Franck,

I currently don't have the time to look into it. I'm still using your single component (DS 1.4). Have no SDK built experience yet. But still want to try it as soon as time allows.

**Comment by franckblais** [comment]
Hello, and thanks :)
Only some of us knows how to do it, so no worries :)

**Comment by KarolKalisz** [comment]
rebuild done on 2.0 and now 3.0 - so all online.
