### ISSUE TITLE
Design studio calendar componen-with features to mark specific date/date range with different color

### ISSUE THREAD

**Issue by raul777** [org-scn-design-studio-community/sdkpackage#65]
Hi Karol,
I tried the calendar component and it was great and as you said in your post at the end, we have the requirement to mark some date/date range with different colors for different purpose, like annual vacation, paid time off, sick day and normal working days.
I am wondering if it's doable and when we could have this new feature.

thanks
Fanchao

**Comment by KarolKalisz** [comment]
Hi, now it is possible to mark up to 10 colors.

**Comment by KarolKalisz** [comment]
will be produced soon.

**Comment by SheenaCelon** [comment]
Hi Karol, 
is this produced? 

Thanks,
Sheena
