### ISSUE TITLE
Data Bound Leader Board (Top/Bottom Selection) Issue

### ISSUE THREAD

**Issue by mdpetersen** [org-scn-design-studio-community/sdkpackage#67]
When doing a top X and there are several members with the same "ranking" the leaderboard show less rows because it doesn't know how to deal with them.

Example: i want to retrieve top 5 countries, as there are several of them with the same value it only shows me the records that can be ranked (in this case only 3) despite of using top 5.
I would suggest if possible to allow the component to show the first members that appear in the list until complete the maximun number.
 
This happens also with bottom X
![leaderboard_options](https://cloud.githubusercontent.com/assets/9642102/11779521/e5d1b8b4-a25b-11e5-8b49-50b3c80d0d95.PNG)
![top5](https://cloud.githubusercontent.com/assets/9642102/11779520/e5cfa844-a25b-11e5-92a6-d75ad1aa1f5c.PNG)

Thanks

**Comment by KarolKalisz** [comment]
Hi, try it now - duplicate values are also shown.

**Comment by mdpetersen** [comment]
Hi Karol

I downloaded the last version   2.0.0.201512171926
Tested and still not working, maybe something went missing in the build?
Few days ago Mike did a change in the pictogram (he added a decimal
precision feature) and is not in this release either.

Again this are screenshots of the issue:

top 6 all values: only shows 5

[image: Imágenes integradas 1]

when filtering by combo box the data source by department: gets worse :(

[image: Imágenes integradas 2]

Thanks for your help on this!

2015-12-17 19:52 GMT+01:00 Karol Kalisz <notifications@github.com>:

**Comment by entmike** [comment]
Hi - The {percent} and decimal precision enhancements have been done in the 3.0 branch that will be released by end of this month (probably next week).  If you are on DS 1.6, you can get a sneak peak of it here: https://github.com/org-scn-design-studio-community/sdkinstall/blob/master/releases/preview/org.scn.community.sdk.package_preview.zip?raw=true

**Comment by mdpetersen** [comment]
Hi guys,

Just downloaded the last package 3.0:
1) pictogram enhancement works good
2) data leaderboard issue not fixed

for a top 5, filter by combo box the data source by department ( you can see in the bar chart that there is data available)

![image](https://cloud.githubusercontent.com/assets/9642102/11951807/4bd8e20c-a894-11e5-9af0-385dee4c345c.png)


Please let me know if you need more information about this issue

Thanks!

**Comment by KarolKalisz** [comment]
Hi,

please check your setting for average. The initial implementation defines TOP as the highest AND higher than calculated average. if your average is set to "-1", it means it will be calculated and then the TOP stops on average - all below average are not TOP any more.

in current implementation you can set the AVERAGE to something like "-9999" and then it should be fixed for you.

but I think this "TOP" is a bit misleading, I will make a property "stop on average" and probably better to make it "false" in default.

the same is for BOTTOM, average is the maximum, all BOTTOMS above average will be ignored. it means in case of BOTTOM you need now manual average on "9999999" or some big number.

does this work?

**Comment by mdpetersen** [comment]
Hi Karol,

Thanks for your reply.

I am not able to find this AVERAGE property (not in property or additional properties panel and neither via script), can you tell me where can i found this?

**Comment by mdpetersen** [comment]
the component i'm using is DATA LEADER BOARD 2.0

**Comment by KarolKalisz** [comment]
ok, I reopen. I think it is my fault - I have made the change for both TOP/FLOP components. forgot leader board. I will check this soon.

**Comment by KarolKalisz** [comment]
Hi, now it should be ok. I have tested with the offline app:
https://github.com/org-scn-design-studio-community/applications/blob/master/SCN_TOP_LEADER-20151223105429.zip

check if this works also for you.

**Comment by mdpetersen** [comment]
Hi Karol,

Just downloaded the last package, I see that you added the new property "Ignore the average", that helps a lot!
Made a couple of tests and works fine, in some cases it retreives more rows than the maximum, but it is a lot better this way!

Thanks for your help!!!
