### ISSUE TITLE
Failed to load Mime object on click on a SCN object + JSON Object APS Errors

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#68]
Hello,

The following error appears after we click on a SCN community component (happened with JSON Object, Embedded Frame, Tree 2.0).
![image](https://cloud.githubusercontent.com/assets/10117707/11842787/e0e33264-a3d3-11e5-8b9f-db69e578e36a.png)

We're a bit concerned about it ...

Also, the JSON Object APS has issues. Alert style messages appears (depending on the version).
At least those messages are displayed:
![image](https://cloud.githubusercontent.com/assets/10117707/11842854/5d4ca9a2-a3d4-11e5-8e71-7d2a7477b660.png)
Also, the APS is not usable to add manual entries.

**Comment by entmike** [comment]
Does clearing IE cache resolve?  We made major source code refactors.

**Comment by franckblais** [comment]
Hey Mike,

Sorry, forgot ton answer your question: we were on the 2.0 branch, not the
new one. I'll test it though :)
Thanks for the support and the hard work !

On Fri, Dec 18, 2015 at 9:38 AM, Mike Howles <notifications@github.com>
wrote:

> Does clearing IE cache resolve? We made major source code refactors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/68#issuecomment-165792210>
> .
>



-- 
Franck BLAIS

**Comment by entmike** [comment]
Assuming it's fixed before we close this one - You good?

**Comment by franckblais** [comment]
Hey Mike,

We've taken the build from last December. The error is still there but it
doesn't bother us anymore as we developped our own JSON component (read a
JSON file on the BO plateform).
I'll close it.

Thanks :)

On Thu, Jan 14, 2016 at 9:16 PM, Mike Howles <notifications@github.com>
wrote:

> Assuming it's fixed before we close this one - You good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/68#issuecomment-171848855>
> .
>



-- 
Franck BLAIS

**Comment by PatrickGodwin** [comment]
Hi Franck,

Reading a JSON file from the platform sounds awesome! Is it a component you would be able to share?

Regards, Pat

**Comment by franckblais** [comment]
Hello Patrick,

Unfortunately, no. It has been developped by a client. But the concept
could be imported and redevelopped inside our extension.
As of now, it is working great, except for one little downside: The content
of the JSON file is available only after the Startup, and cannot be inside
the same method (1/ Set JSON File 2/ Read entries = do not work in same
method, an event on the JSON config app is required).

If I find some time, I'll try to implement it on our JSON component. I have
also some improvements of the hierarchical menu (getMembers on hierarchy
masterdata).

On Tue, Feb 2, 2016 at 5:04 AM, PatrickGodwin <notifications@github.com>
wrote:

> Hi Franck,
>
> Reading a JSON file from the platform sounds awesome! Is it a component
> you would be able to share?
>
> Regards, Pat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/org-scn-design-studio-community/sdkpackage/issues/68#issuecomment-178488966>
> .
>



-- 
Franck BLAIS
