### ISSUE TITLE
Error installing 3.0 Data Sources components on platform

### ISSUE THREAD

**Issue by alfgon** [org-scn-design-studio-community/sdkpackage#70]
Hi,

 We have just downloaded new SDk extensions release (3.0) for DS 1.6. When installing components on platform following error message appears

![kk](https://cloud.githubusercontent.com/assets/10329124/11952648/645e9a1e-a89a-11e5-81c6-8d3b7713a79a.jpg)

So, we can not install SDK data sources component on server.

thx

**Comment by KarolKalisz** [comment]
cool, thanks for opening here. check out the updated version. corrected with https://github.com/org-scn-design-studio-community/sdkpackage/commit/e0b9e5bf2c2aa97111b178eeaebf2b417654b52a
