### ISSUE TITLE
sdk package for 1.5 (version 15.2.0) not available

### ISSUE THREAD

**Issue by emirado** [org-scn-design-studio-community/sdkpackage#72]
Hi,
could you please share or restore 2.0 (DS 1.5) package version on http://org-scn-design-studio-community.github.io/sdkinstall/web/20/components/index.html
Now only 1.6 is available under both links. This doesn't work in 1.5 due to 

      <import plugin="com.sap.ip.bi.zen.rt.components.sdk.eclipse" version="16.0.0" match="greaterOrEqual"/>

in feature.xml

Thx

**Comment by KarolKalisz** [comment]
thanks. the link was incorrectly linking the 3.0 release, now it links 2.0 release.
