### ISSUE TITLE
fiori components do not work in scripting (m mode)

### ISSUE THREAD

**Issue by KarolKalisz** [org-scn-design-studio-community/sdkpackage#74]
issue 1 for.
http://scn.sap.com/community/businessobjects-design-studio/blog/2014/12/10/scn-design-studio-sdk-development-community#comment-642296

**Comment by mikezaschka** [comment]
It seems this is not fixed. With the current release from http://org-scn-design-studio-community.github.io/sdkinstall/web/components/ (preview and stable) I am not able to access the created Fiori components via scripting nor can I use the scripting events.
