### ISSUE TITLE
Tree 2.0 Improvements

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#76]
Hello,

We're using the Tree 2.0 and it's working well, as designed.
Nevertheless, I've thought of potential improvements:
* Identify the selected item (add a class like SapUiNodeSelected)
* Option to set tree expanded by default
* Activate / Deactivate collapsing (if somebody wants a static menu tree).

Basically, we're using it to generate a selection menu for a portal with a viewing frame embedded.

**Comment by KarolKalisz** [comment]
Hi Franck,

as far small change was possible...
- the selected item is already marked by UI5 class (you can see the selection) and you can overwrite it if required.
- this option was possible (there is a flag for it now)
- this is too difficult for this component (at least I have not found a working solution in short time frame)

Karol
