### ISSUE TITLE
Databound for the Activity Viewer (Manual Gantt Chart)

### ISSUE THREAD

**Issue by arunnesh** [org-scn-design-studio-community/sdkpackage#77]
Hi Karol,

I have attached the sample CSV and the Layout file for the Gantt Chart. Can you please help us in making it as Databound to work on the Activity Viewer Component? 

If possible can you please make it as a Separate file instead of adding it to the SDK Package with all the other components. 

Thanks,
Arunnesh
[Activity Viewer -Gantt Chart.zip](https://github.com/org-scn-design-studio-community/sdkpackage/files/81413/Activity.Viewer.-Gantt.Chart.zip)
![tender sdk image](https://cloud.githubusercontent.com/assets/16595108/12176225/6899830e-b534-11e5-9ca0-01aca1bb8a9d.jpg)

**Comment by KarolKalisz** [comment]
Hi Arunnesh,

first, can you please check if it would work for you as described in this blog - http://scn.sap.com/community/businessobjects-design-studio/blog/2015/06/17/design-studio-15-data-binding--using-formatter-functions-for-advanced-logic

the idea from this blog is to use the data binding on some property and use the formatter function to call methods which can fill in the component.

Karol

**Comment by KarolKalisz** [comment]
Hi Arunnesh,

I have considered this topic. The main issue is - it is hard to match automatically from data source to the component specific requriements. In the meantime I use this component internally for me with the data iterator from mike and using the script methods it is really easy to modify it.

http://scn.sap.com/community/businessobjects-design-studio/blog/2016/02/08/design-studio-16-sdk--data-iterator--read-your-data-row-by-row-finally

so, I do not think we will make it data bound.

Karol
