### ISSUE TITLE
KPI Tile 2.0 in Design Studio 1.6 does not work

### ISSUE THREAD

**Issue by nazeer1232** [org-scn-design-studio-community/sdkpackage#81]
Dear Friends,
I downloaded the sdk kit for 1.6 version and when I am trying to open KPI tile 2.0 component on blue crystal theme on DS 1.6 client the refresh page just clicks forever. 

![image](https://cloud.githubusercontent.com/assets/16689762/12302487/7806aaae-ba36-11e5-9b02-e9204c2f32f1.png)

Please advice.

**Comment by entmike** [comment]
I've fixed it.  Will upload correction tonight.

**Comment by entmike** [comment]
![tile fixed](https://cloud.githubusercontent.com/assets/174348/12342947/fd12b5b2-baf4-11e5-80d4-6b5803dd04c5.png)

**Comment by entmike** [comment]
Fix uploaded to downloadable .zip

**Comment by tobim889** [comment]
Hi, 
i am a bit new to github - how to get this fix? 
is there a package like "org.scn.community.sdk.package_stable.zip"?
Sorry for this noob question:)
BR,
Tobias

**Comment by tuscanlabs** [comment]
Hi,

I am using the KPI Tile 2.0 and the add property works the first time but not after.

KPITILE_FI.addProperty('TITLE', 'text', 'Dashboard');    --> This is what displays on the screen.
KPITILE_FI.addProperty('TITLE', 'text', 'Report');

another scenario where it does not work
KPITILE_FI.addProperty('TITLE', 'text', 'Dashboard');    --> This is what displays on the screen.
KPITILE_FI.addProperty('FOOTER', 'text', 'In Process');  --> This does not update
