### ISSUE TITLE
BulletChart

### ISSUE THREAD

**Issue by shlomiweiss** [org-scn-design-studio-community/sdkpackage#83]
Hi

I'm trying to show a simple bullet Chart that shows actual versus Target value.
A simple chart that will show that we have covered, for example 70% of our target and will also show the actual and target values.
We used to cover that with a gauge component in Dashboards but there is no Gauge in design studio and not also in Utility pack 3.0
I also tried to configure the Bullet chart to do it and could find a way
There is also very little documentation on the Billet chart and micro bullet chart.
I suggest to post some simple YouTube videos.

Thanks

Shlomi

**Comment by KarolKalisz** [comment]
Hello Shlomi,

I would recommend you for this to use Scorecard in 1.6 release, then you are on "standard" side. Also, there is "Gauge (Speedometer)" component.

For bullet chart, we will need to check for some example.
Please check the Scorecard, it has also bullet charts.

Karol

**Comment by KarolKalisz** [comment]
Hi Shlomi,

is this issue still active for you?

Karol

**Comment by KarolKalisz** [comment]
closing after inactivity, reopen if required.
