### ISSUE TITLE
Gauge in auto width and height mode

### ISSUE THREAD

**Issue by shlomiweiss** [org-scn-design-studio-community/sdkpackage#84]
Hi

The is an issue with he old speedometer component and in the new Gauge
When I set the width or height to 'auto' it completely disappears in runtime
I will appreciate if that could be fixed,
that is the only thing that is holding me on upgrading and old Dashboard to Design studio

Shlomi

**Comment by shlomiweiss** [comment]
Hi

I've tested the new version and it has some improvement on the Gauge component
Now I can set auto width and auto height and it is shown in run time
The issue is that it doesn't work when the component is inside a grid layout
Please check and update

Thanks

Shlomi

**Comment by KarolKalisz** [comment]
works, but you have to deactivate title as this is wrongly resizing. I hope this is ok. alternatively, you can redefine css for title on your own.

**Comment by shlomiweiss** [comment]
Hi thanks
How do I decativate title?
Just deleting the content of the title didn't help

**Comment by KarolKalisz** [comment]
for me just removing the title in properties makes it invisible and this works. if you want some title, use text component above to make it - then you can make it also resizable.

what does not work?

**Comment by JanWe92** [comment]
Hi,

I have implemented a gauge in a grid and I set width and height to "auto". I have no title set, but the gauge is not appearing. How could I solve this issue?

Thanks for help!
