### ISSUE TITLE
Client Information as a Technical Component loses "own" information in version 3.x

### ISSUE THREAD

**Issue by mikezaschka** [org-scn-design-studio-community/sdkpackage#85]
In prior releases the Client Information component could be placed inside container components. The internal API allowed to reference and read the parent components width and height information (me.getOwnwidth(), etc.).
As the Client Information is now a Technical Component and there is no way to bind the component to a container, the own information is not available anymore. Instead the full application sizes are always returned.

**Comment by entmike** [comment]
I will fix this this evening

**Comment by entmike** [comment]
Fixing today.

**Comment by entmike** [comment]
Fixed and available for download.
