### ISSUE TITLE
issue with Fioti toolbar on m-mode

### ISSUE THREAD

**Issue by alfgon** [org-scn-design-studio-community/sdkpackage#86]
Hi,

 When using firori tool bar component on m-mode buttons does not reneder properly (see attached picture)

![kk2](https://cloud.githubusercontent.com/assets/10329124/12607032/2c765ba6-c4d2-11e5-8ec2-dc5b3adae93f.jpg)

**Comment by entmike** [comment]
Fixed and available for download.
