### ISSUE TITLE
FioriButton setIcon method only works first time

### ISSUE THREAD

**Issue by alfgon** [org-scn-design-studio-community/sdkpackage#87]
Hi,

 I am using the FioriButton. I am trying to use a single button that changes its behaviour after clicking on it using a code as sample below (implemented on event click button)

// Display Mode Chart and button is clicked
if (g_DisplayMode == 0) {

	PANEL_CROSSTAB.setVisible(true);
	PANEL_CHART.setVisible(false);
	
	DISPLAY_BUTTON.setTooltip("Chart Mode");
	DISPLAY_BUTTON.setIcon("e18c");
	
	g_DisplayMode = 1;
}
// Display Mode Table and button is clicked
else if (g_DisplayMode == 1) {

	PANEL_CROSSTAB.setVisible(false);
	PANEL_CHART.setVisible(true);
	
	DISPLAY_BUTTON.setTooltip("Table Mode");
	DISPLAY_BUTTON.setIcon("e0ba");
	
	g_DisplayMode = 0;

}
Initially g_DisplayMode is set 1. First time button is clicked all works fine. icon and tooltip text is replaced. By after clicking again on it only tooltip text is updated. The icon not. 

?? bug

**Comment by KarolKalisz** [comment]
found, fixed, will be available in 2 hours from now as download.

**Comment by KarolKalisz** [comment]
Sorry, I could not get it produced today, i will make it tomorrow.

**Comment by alfgon** [comment]
Thanks Karol!
