### ISSUE TITLE
"Postresponseparser2.0" miss some critical API

### ISSUE THREAD

**Issue by willyyen** [org-scn-design-studio-community/sdkpackage#88]
Hello Expert
I am using the component "Postresponseparser"  which works very well in version 2.0.
 
But When I upgrade to SDK version 3.0. I found that some of API cannot be found.
Ex: I can use the function  "add parameter"  in version 2.0 but I cannot found in  "Postresponseparser 2.0" in version 3.0.  

Is there anything I miss?

**Comment by KarolKalisz** [comment]
releases produced with changes (preview, stable). The issue was, I probably forgot to define the specification correctly during the work on 3.0.

one wish - please check it and comment if it works correctly.

**Comment by willyyen** [comment]
Hi Karol

Thank you for the quick fix.
It works well now.
:)

Willy
