### ISSUE TITLE
SCN Design Studio 1.6 SDK Components (ver 3.0)

### ISSUE THREAD

**Issue by mikecurtis11** [org-scn-design-studio-community/sdkpackage#90]
Hi All,

I am trying to install SCN Design Studio 1.6 SDK Components (ver 3.0) tried online and offline options but I keep getting the same below error message:

Cannot complete the install because one or more required items could not be found.

Software currently installed: SAP BusinessObjects Design Studio 15.2.0 (com.sap.ip.bi.zen.product.platform 15.2.0)

Missing requirement: SAP BusinessObjects Design Studio 15.2.0 (com.sap.ip.bi.zen.product.platform 15.2.0) requires 'toolingcom.sap.ip.bi.zen.product.platform.configuration [15.2.0]' but it could not be found

Has anyone faced the same issue? Am I missing any perquisite steps?

**Comment by franckblais** [comment]
Hi Mike,

Version 3.0 has been compiled for 1.6+ only.
You can use version 2.0 for 1.5+:
http://org-scn-design-studio-community.github.io/sdkinstall/web/20/components/index.html

**Comment by mikecurtis11** [comment]
Thank you for you response. You were right...figured that despite my client version was 1.6 previous installation were causing a version conflict..
