### ISSUE TITLE
Design Studio SDK Sample error portal runtime / Web Item …could not be found in current Web Application

### ISSUE THREAD

**Issue by michaelwecker** [org-scn-design-studio-community/sdkpackage#91]
Hello,
 
we got the following problem:
 
Design Studio 1.5 SP6 corrosponding Design Studio Netweaver Add On Netweaver Portal  7.31 SP 012
 
We want to use a SDK Component of the on SDN published components within a Design Studio application.
 
http://org-scn-design-studio-community.github.io/sdkinstall/web/components/
 
We are hosting the Design Studio in this special situation on the Netweaver Plattform with the Netweaver Add On.
 
The Design Studio applicaions are executable within the Netweaver / portal runtime without any problems.
 
We installed the SDK Components of SDN locally within the Client and afterworks on the Netweaver Plattform successfully.
 
Afterwards we restarted the portalcomponents as discribed.
 
The SDK components are running fine within local mode but are not executable within the portal runtime.
 
The applicaion itself with the standard components is running with only the SDK Components are not showing.
 
Error Messages are: 

**"Web Item with name UI5TABLE_1 could not be found in current Web Application"
 
"ITEM" of type "ORG_SCN_COMMUNITY_DATABOUND_UI5TABLE"  could not be generated"**
   
We checked everything double and we deinstalled and installed again the SDK components and restarted the complete system and we still are facing the same errors.
 
Do you got any idea? 
 
Thank you very much for your support.
 
Best regards
 
Michael Wecker

**Comment by KarolKalisz** [comment]
Hi Michael,

Have you installed all bundled into the portal? This error is when the component cannot be found by the system.

Karol

**Comment by michaelwecker** [comment]
Hello Karol,

yes we installed the complete bundle and restarted the system but without any solution. Do you got any additional idea? 
Thanks
Michael

**Comment by MartinPankraz** [comment]
Hi Michael,

Can you please check on the NW portal if the nodes starting with com.sap.ip.bi.designstudio.* are all up? In addition to that you should check the portal logs on NWA. In there you will see if the SDK components were loaded successfully. Judging from your description NW portal is not loading SDK at all. Check with you SAP basis to resolve that.

Regards
Martin

**Comment by KarolKalisz** [comment]
Hi Michael, 

any solution on your side until today? there is another thread on SCN http://scn.sap.com/thread/3881283 whit exactly same issue.

If there is no solution - someone needs to open incident to check it directly on the system.

Karol

**Comment by MartinPankraz** [comment]
Hi Michael,

I had the same problem last week. On our end bw_service user was duplicated. Once deleted and a restart of the java stack the portal started loading the SDK extensions again.

Regards
Martin

**Comment by michaelwecker** [comment]
Hi Martin, 
thanks for the reply, I will check that. 

We uninstalled every SDK component from plattform, reinstalled with every step in installation guide but without any success. 
We are still facing the same problem. 
Nodes are all up.

I got a specific question:
Where can I see exactly in the portal logs if the SDK components were loaded successfully? 

We were searching quite long but we found nothing.

Thank you 

Best regards 
Michael Wecker

**Comment by MartinPankraz** [comment]
Hi Michael,

SAP has a guide called TroubleshootingSDK.docx downloadable on of the NW related DesignStudio notes. In there you will find directions how to check SDK loading status on NWA. Actually there is also an entry on SCN regarding the same or at least a similar problem:

http://scn.sap.com/message/16605172#16605172 

Kind regards
Martin

**Comment by michaelwecker** [comment]
Hello Martin, 
we still have the same problem, I answered within the scn discussion. Maybe you can have a look. 
Thank you 
Michael

**Comment by MartinPankraz** [comment]
Hi Michael,

I answered the question on SCN so that Robert can also see the current status. Apart from that this is a SAP basis problem and not related to the DesignStudio SDK repository. Therefore the discussion should continue on SCN and not here.

Kind regards
Martin
