### ISSUE TITLE
Accordion Menu - MaxSectionHeight set to Auto based on dimension values

### ISSUE THREAD

**Issue by mails2raghav** [org-scn-design-studio-community/sdkpackage#92]
At times, we would hit the issue of not having enough room for few elements run over max height size. It would be great, if maxsectionheight can be dynamically set based on dimension values and also add additional property to select the element.
 
Can you please share Accordion SDK ?

**Comment by KarolKalisz** [comment]
Hi,

can you please specify what you expect? ist it like defining the section size per section (currently all have only one max size) or what kind of logic you want to see?

Technically, it would be possible to allow setting of the height per section - but how much will it help? you can already define the height of the section to a value which will be the maximum you can provide for the control. Eg. control height is 800px, you have 3 sections, so the section height can be set to 800 - 3x27px (height of the headers) == 719 px.

can you please give some screenshots and more explanation?

for selection, there is already event "on selection changed" where you can get the key of element the user has selected.

Karol

**Comment by mails2raghav** [comment]
Hi Karol,

Thanks for taking time to respond to the query. We are are looking for 'defining the section size per section based on dimension values'

Example: If we have 2 dimension hierarchy **Country -> Cities**, to display each country section and cities as elements, number of cities may vary depends on countries. If we set the height as 500, the same maxsection height is applicable for countries with 2 cities and with 20 cities which looks awkward when the user expand the section. 

I hope it clarifies the required. Please let me know if you might need more information.

Thanks
Raghav

**Comment by KarolKalisz** [comment]
Hi, you can find new optional parameter in accordion sections array. If there will be a value, it will overwrite the maximum height (common for all sections).

in script, you can adjust it by method

	/**
	 * Sets the Height for Section Key<br/>
	 */
	void setSectionHeight (
			/**/ String key,
			/**/ int height
			) 

or as last optional parameter when adding section

will this help?
