### ISSUE TITLE
Error using Data Iterator with DS 1.6

### ISSUE THREAD

**Issue by alllright** [org-scn-design-studio-community/sdkpackage#94]
Hello gurus,

Sorry to bother you guys.
I'm trying to use a Data Iterator Component on a dashboard but i'm getting the same error over and over again.

This error only occurs when i try to call the data iterator name on the script (no matter what method i use with it, i still get the same error). The binded data source was created using an UNX universe.

All the minimum basic requirements are there (query with at least 1 measure and it is a very simple one, resulting only in 3 rows and 2 colums).

The only code line i'm using to test the component is: `DATAITERATOR_2.getDimensions();` but actually it doesn't matter which method i try, because i will always get this error. This code is placed on StartUp Events.

The error disappears if i delete this line (or any line referring to this component).

I've provided you the error log file.
[error_full.txt](https://github.com/org-scn-design-studio-community/sdkpackage/files/198257/error_full.txt)

Thank you in advance.

Joaquim Amorim
SAP BA Consultant
Lisbon, Portugal

**Comment by alllright** [comment]
Hello again,

After a good night sleep i've come across with a solution. I've moved the data iterator script code from Project:Events:onStartUp to DataIterator:Events:OnDataChange.

On startUp Event, the only thing i need to keep there (along side with the rest of the code, of course) was the line DATASOURCENAME.loadDataSource(); where DATASOURCENAME is the data source that has already been binded to the Data Iterator.

Cheers y'all.

With that change, the error stops appearing and it works like a charm.

**Comment by KarolKalisz** [comment]
great! self-repairing problems are the best ;-)
