### ISSUE TITLE
Simple Date: Javascript error

### ISSUE THREAD

**Issue by oemo** [org-scn-design-studio-community/sdkpackage#98]
Creating an empty application with a SIMPLEDATE component and a button with the following code

`SIMPLEDATE_1.initializeWithInternalDate(APPLICATION.getInfo().dateNowInternalFormat);`

Gets me this javascript error when clicking the button:

> A JavaScript error occurred. Die Eigenschaft "dispatchProperties" eines undefinierten oder Nullverweises kann nicht abgerufen werden. TypeError: Die Eigenschaft "dispatchProperties" eines undefinierten oder Nullverweises kann nicht abgerufen werden. at dispatchProperties (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:279305) at update (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:261020) at updateComponent (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:140634) at dispatchUpdateControl (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:122413) at dispatchDelta (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:104640) at dispatch (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:135153) at sapbi_phx_process_json (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:85250) at sapbi_phx (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:87063) at callback (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:10313:84572) at context.execCb (http://localhost:58621/aad/zen/mimes/combined_static_includes_1.js?version=20151112172347:1:20714)
> Please contact your application designer

Can anyone reproduce this?

**Comment by MartinPankraz** [comment]
Hi oemo,

I just tested with the current version. There is no error. Updating the components will probably fix your issue.

Let us know.

Kind regards
Martin

**Comment by KarolKalisz** [comment]
Hi oemo,

can you please check if you use simple date in 3.0 release as Technical Component or you have it as Standard Component in your canvas? It is possible, that you have to remove it in case you have it in canvas and insert as technical component. Reason is, technical components do not have rendering part - and we moved them from Utils to Technical Components in 3.0 release.

Karol

**Comment by KarolKalisz** [comment]
please reopen if the answers above will not help.

**Comment by oemo** [comment]
After updating from 3.0.0.201602261531 to 3.0.0.201606061005 it's working fine. Thanks and sorry for the late reply!
