### ISSUE TITLE
RealDate: Issue with day number in Tenth (10, 20, 30)

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#99]
Hi,

We found out an issue with RealDate where when the day number is either 10 20 or 30, the wrong data is returned.
For instance: initialize with 20160110. Get the day number: Wrong.

**Comment by MartinPankraz** [comment]
Hi Franck,

I just fixed the bug. The next build will get you the corrected version.

Kind regards
Martin

**Comment by franckblais** [comment]
Thanks Martin :)
